### ISSUE TITLE
Error deploying app in Docker

### ISSUE THREAD

**Issue by kkallakuri** [Children-in-Families/oscar-web#1825]
Following directions outlined in OSCaR Private Hosting Guide. Hitting a roadblock when deploying or starting the app in the container. We have not deployed the OSCaR in AWS, but using Ubuntu deployed in VMWare Workstation. All the steps execute fine and the app is complied fine. 

Do we need to make changes in envirmnets file, as the failure is coming from /app/config.ru. Please see the attached log file.
[app.txt](https://github.com/DevZep/oscar-web/files/6274829/app.txt)

**Comment by kirykr** [comment]
> Following directions outlined in OSCaR Private Hosting Guide. Hitting a roadblock when deploying or starting the app in the container. We have not deployed the OSCaR in AWS, but using Ubuntu deployed in VMWare Workstation. All the steps execute fine and the app is complied fine.
> 
> Do we need to make changes in envirmnets file, as the failure is coming from /app/config.ru. Please see the attached log file. [app.txt](https://github.com/DevZep/oscar-web/files/6274829/app.txt)

We updated the Dockerfile. You can pull from master branch and try it again.
